[package]
name = "capara"
version = "0.1.1"
edition = "2018"
authors = ["Aviram Hassan <aviramyhassan@gmail.com>"]

[lib]
name = "capara"
crate-type = ["cdylib"]

[dependencies.pyo3]
git = "https://github.com/pyo3/pyo3"
features = ["extension-module"]